name: Atualizar README com arquivos e data

on:
  push:
    paths:
      - '**.pbix'
      - '**.xlsx'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositÃ³rio
      uses: actions/checkout@v3

    - name: Atualizar README mantendo conteÃºdo
      run: |
        INFO="## RelatÃ³rios Power BI\nðŸ“… Ãšltima atualizaÃ§Ã£o: $(LC_TIME=pt_BR.UTF-8 TZ=America/Sao_Paulo date '+%A, %d de %B de %Y - %H:%M')\n\nðŸ“‚ Arquivos no repositÃ³rio:"
        LISTA=$(find . -type f \( -iname "*.pbix" -o -iname "*.xlsx" \))
        ANTIGO=$(cat README.md)
        echo -e "$INFO\n$LISTA\n\n$ANTIGO" > README.md


    - name: Fazer commit e push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Atualiza README automaticamente"
        git push
